Attribute VB_Name = "RegexErrors"
Option Explicit

Public Enum RegexErrType
    REGEX_ERR = vbObjectError + 3000
    
    REGEX_ERR_INVALID_REGEXP_ESCAPE = REGEX_ERR + 1
    REGEX_ERR_INVALID_ESCAPE = REGEX_ERR + 2
    REGEX_ERR_INVALID_RANGE = REGEX_ERR + 3
    REGEX_ERR_UNTERMINATED_CHARCLASS = REGEX_ERR + 4
    REGEX_ERR_INVALID_REGEXP_GROUP = REGEX_ERR + 6
    REGEX_ERR_INVALID_REGEXP_CHARACTER = REGEX_ERR + 7
    REGEX_ERR_INVALID_QUANTIFIER = REGEX_ERR + 8
    REGEX_ERR_UNEXPECTED_END_OF_PATTERN = REGEX_ERR + 9
    REGEX_ERR_UNEXPECTED_REGEXP_TOKEN = REGEX_ERR + 10
    REGEX_ERR_UNEXPECTED_CLOSING_PAREN = REGEX_ERR + 11
    REGEX_ERR_INVALID_QUANTIFIER_NO_ATOM = REGEX_ERR + 12
    REGEX_ERR_INVALID_IDENTIFIER = REGEX_ERR + 13
    REGEX_ERR_INVALID_MODIFIER = REGEX_ERR + 14
    
    REGEX_ERR_INTERNAL_LOGIC_ERR = REGEX_ERR + 20
    
    REGEX_ERR_INVALID_FLAG_ERR = REGEX_ERR + 30
    REGEX_ERR_INVALID_REPLACEMENT_STRING = REGEX_ERR + 31
    
    REGEX_ERR_INVALID_INPUT = REGEX_ERR + 50
End Enum
