Attribute VB_Name = "RegexErrors"
Option Explicit

Public Const REGEX_ERR = vbObjectError + 3000

Public Const REGEX_ERR_INVALID_REGEXP_ESCAPE = REGEX_ERR + 1
Public Const REGEX_ERR_INVALID_ESCAPE = REGEX_ERR + 2
Public Const REGEX_ERR_INVALID_RANGE = REGEX_ERR + 3
Public Const REGEX_ERR_UNTERMINATED_CHARCLASS = REGEX_ERR + 4
Public Const REGEX_ERR_INVALID_REGEXP_GROUP = REGEX_ERR + 6
Public Const REGEX_ERR_INVALID_REGEXP_CHARACTER = REGEX_ERR + 7
Public Const REGEX_ERR_INVALID_QUANTIFIER = REGEX_ERR + 8
Public Const REGEX_ERR_UNEXPECTED_END_OF_PATTERN = REGEX_ERR + 9
Public Const REGEX_ERR_UNEXPECTED_REGEXP_TOKEN = REGEX_ERR + 10
Public Const REGEX_ERR_UNEXPECTED_CLOSING_PAREN = REGEX_ERR + 11
Public Const REGEX_ERR_INVALID_QUANTIFIER_NO_ATOM = REGEX_ERR + 12
Public Const REGEX_ERR_INVALID_IDENTIFIER = REGEX_ERR + 13

Public Const REGEX_ERR_INTERNAL_LOGIC_ERR = REGEX_ERR + 20

Public Const REGEX_ERR_INVALID_FLAG_ERR = REGEX_ERR + 30
Public Const REGEX_ERR_INVALID_REPLACEMENT_STRING = REGEX_ERR + 31

Public Const REGEX_ERR_INVALID_INPUT = REGEX_ERR + 50

